/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionConfirm: typeof import('./../components/common/ActionConfirm.vue')['default']
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./../components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./../components/layout/AppSidebar.vue')['default']
    BarChart: typeof import('./../components/charts/BarChart.vue')['default']
    CodeBlock: typeof import('./../components/common/CodeBlock.vue')['default']
    DataTable: typeof import('./../components/common/DataTable.vue')['default']
    DrillStatusBadge: typeof import('./../components/common/DrillStatusBadge.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyBox: typeof import('./../components/common/EmptyBox.vue')['default']
    GaugeChart: typeof import('./../components/charts/GaugeChart.vue')['default']
    HeatmapChart: typeof import('./../components/charts/HeatmapChart.vue')['default']
    LineChart: typeof import('./../components/charts/LineChart.vue')['default']
    LoadingCard: typeof import('./../components/common/LoadingCard.vue')['default']
    NotificationList: typeof import('./../components/notifications/NotificationList.vue')['default']
    NotificationPopover: typeof import('./../components/notifications/NotificationPopover.vue')['default']
    PieChart: typeof import('./../components/charts/PieChart.vue')['default']
    RadarChart: typeof import('./../components/charts/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineChart: typeof import('./../components/charts/TimelineChart.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
