/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountdownTimer: typeof import('./components/CountdownTimer.vue')['default']
    DrillFlowChart: typeof import('./components/DrillFlowChart.vue')['default']
    MessageTicker: typeof import('./components/MessageTicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
  }
}
